### ISSUE TITLE
Error creating bean with name 'patchMathRandom' with Java version: Oracle 19

### ISSUE THREAD

**Issue by JavierYuste** [mork-optimization/mork#103]
Version of Java: Oracle 19

```
[13:33:31] INFO e.u.e.grafo.SCP_v012.Main  : Starting Main using Java 19.0.1 on YUSTE with PID 18428 (C:\Users\javie\IdeaProjects\SCP_v012\target\classes started by javie in C:\Users\javie\IdeaProjects\SCP_v012)
[13:33:31] INFO e.u.e.grafo.SCP_v012.Main  : No active profile set, falling back to default profiles: default
[13:33:33] INFO e$BeanPostProcessorChecker : Bean 'eventAsyncConfigurer' of type [es.urjc.etsii.grafo.solver.services.events.EventAsyncConfigurer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[13:33:34] INFO .s.b.w.e.t.TomcatWebServer : Tomcat initialized with port(s): 8080 (http)
[13:33:34] INFO o.a.c.c.StandardService    : Starting service [Tomcat]
[13:33:34] INFO o.a.c.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.55]
[13:33:34] INFO o.a.c.c.C.[.[.[/]          : Initializing Spring embedded WebApplicationContext
[13:33:34] INFO ebServerApplicationContext : Root WebApplicationContext: initialization completed in 2971 ms
[13:33:34] WARN ebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patchMathRandom': Invocation of init method failed; nested exception is java.lang.UnsupportedOperationException
[13:33:34] INFO o.a.c.c.StandardService    : Stopping service [Tomcat]
[13:33:34] INFO ationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[13:33:34] ERROR o.s.b.SpringApplication    : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patchMathRandom': Invocation of init method failed; nested exception is java.lang.UnsupportedOperationException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar:2.6.1]
	at es.urjc.etsii.grafo.solver.Mork.start(Mork.java:27) ~[mork-0.12.jar:0.12]
	at es.urjc.etsii.grafo.SCP_v012.Main.main(Main.java:7) ~[classes/:na]
Caused by: java.lang.UnsupportedOperationException: null
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118) ~[na:na]
	at es.urjc.etsii.grafo.patches.PatchMathRandom.makeNonFinal(PatchMathRandom.java:63) ~[mork-0.12.jar:0.12]
	at es.urjc.etsii.grafo.patches.PatchMathRandom.patch(PatchMathRandom.java:49) ~[mork-0.12.jar:0.12]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.13.jar:5.3.13]
	... 17 common frames omitted


Process finished with exit code 1
```

**Comment by rmartinsanta** [comment]
Changed in Java 18, may be related: https://bugs.openjdk.org/browse/JDK-8281168
[JDK-8281168] Micro-optimize VarForm.getMemberName for interpreter - Java Bug System - bugs.openjdk.org<https://bugs.openjdk.org/browse/JDK-8281168>
I was looking for easy things to do to improve java.lang.invoke cold performance. One of the things is inlining VarForm.getMemberName a bit, so that interpreter does not have to call through getMemberNameOrNull.
bugs.openjdk.org

________________________________
De: Javier Yuste ***@***.***>
Enviado: jueves, 27 de octubre de 2022 13:37
Para: rmartinsanta/mork ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [rmartinsanta/mork] Error creating bean with name 'patchMathRandom' in Java 19 (Issue #103)


Version of Java: Oracle 19

[13:33:31] INFO e.u.e.grafo.SCP_v012.Main  : Starting Main using Java 19.0.1 on YUSTE with PID 18428 (C:\Users\javie\IdeaProjects\SCP_v012\target\classes started by javie in C:\Users\javie\IdeaProjects\SCP_v012)
[13:33:31] INFO e.u.e.grafo.SCP_v012.Main  : No active profile set, falling back to default profiles: default
[13:33:33] INFO e$BeanPostProcessorChecker : Bean 'eventAsyncConfigurer' of type [es.urjc.etsii.grafo.solver.services.events.EventAsyncConfigurer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[13:33:34] INFO .s.b.w.e.t.TomcatWebServer : Tomcat initialized with port(s): 8080 (http)
[13:33:34] INFO o.a.c.c.StandardService    : Starting service [Tomcat]
[13:33:34] INFO o.a.c.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.55]
[13:33:34] INFO o.a.c.c.C.[.[.[/]          : Initializing Spring embedded WebApplicationContext
[13:33:34] INFO ebServerApplicationContext : Root WebApplicationContext: initialization completed in 2971 ms
[13:33:34] WARN ebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patchMathRandom': Invocation of init method failed; nested exception is java.lang.UnsupportedOperationException
[13:33:34] INFO o.a.c.c.StandardService    : Stopping service [Tomcat]
[13:33:34] INFO ationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[13:33:34] ERROR o.s.b.SpringApplication    : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patchMathRandom': Invocation of init method failed; nested exception is java.lang.UnsupportedOperationException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.13.jar:5.3.13]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar:5.3.13]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1.jar:2.6.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar:2.6.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar:2.6.1]
        at es.urjc.etsii.grafo.solver.Mork.start(Mork.java:27) ~[mork-0.12.jar:0.12]
        at es.urjc.etsii.grafo.SCP_v012.Main.main(Main.java:7) ~[classes/:na]
Caused by: java.lang.UnsupportedOperationException: null
        at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118) ~[na:na]
        at es.urjc.etsii.grafo.patches.PatchMathRandom.makeNonFinal(PatchMathRandom.java:63) ~[mork-0.12.jar:0.12]
        at es.urjc.etsii.grafo.patches.PatchMathRandom.patch(PatchMathRandom.java:49) ~[mork-0.12.jar:0.12]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.13.jar:5.3.13]
        ... 17 common frames omitted


Process finished with exit code 1

**Comment by rmartinsanta** [comment]
Java 21 LTS is going to be published next week. Since [the new reflection behavior with method handles](https://openjdk.org/jeps/416) is maintained, the patch for Math.random() is now always blocked. If I dont find a way to bypass the new restrictions I will remove it. For now, allow it to gracefully fail with a warning.
