### ISSUE TITLE
Autoconfig @CategoricalParam error with Integer and Boolean.

### ISSUE THREAD

**Issue by isaaclo97** [mork-optimization/mork#170]
**Describe the bug**
CategoricalParam element with boolean and integer values have been created.

**To Reproduce**
Autoconfig method with parameters like: @CategoricalParam(strings = {"true","false"}) or @CategoricalParam(strings = {"1","0"})

**Expected behavior**
Assignment and conversion of the values into the appropriate variables for each of them.

**What happens instead**
Failed to find constructor method.

**Screenshots / Code snippets**
```
es.urjc.etsii.grafo.autoconfig.exception.AlgorithmParsingException: Failed to find constructor method in class ************ for params {{*********=0, firstImprove=1}, types {*********=class java.lang.String, firstImprove=class java.lang.String}
	at es.urjc.etsii.grafo.autoconfig.AlgorithmBuilderUtil.build(AlgorithmBuilderUtil.java:37) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.service.AlgorithmBuilderService.buildAlgorithmComponentByName(AlgorithmBuilderService.java:58) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.AlgorithmBuilderListener.exitComponent(AlgorithmBuilderListener.java:34) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.antlr.AlgorithmParser$ComponentContext.exitRule(AlgorithmParser.java:158) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62) ~[antlr4-runtime-4.12.0.jar!/:4.12.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:38) ~[antlr4-runtime-4.12.0.jar!/:4.12.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.12.0.jar!/:4.12.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.12.0.jar!/:4.12.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.12.0.jar!/:4.12.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.12.0.jar!/:4.12.0]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.12.0.jar!/:4.12.0]
	at es.urjc.etsii.grafo.autoconfig.service.AlgorithmBuilderService.buildAlgorithmComponentFromString(AlgorithmBuilderService.java:86) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.service.AlgorithmBuilderService.buildAlgorithmFromString(AlgorithmBuilderService.java:69) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.irace.AutomaticAlgorithmBuilder.buildFromStringDescription(AutomaticAlgorithmBuilder.java:53) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.irace.AutomaticAlgorithmBuilder.buildFromConfig(AutomaticAlgorithmBuilder.java:59) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.irace.IraceOrchestrator.iraceCallback(IraceOrchestrator.java:246) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.execute(ExecutionController.java:53) ~[autoconfig-0.17-SNAPSHOT.jar!/:0.17-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.8.jar!/:6.0.8]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.8.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.8.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Versions (ignore not applicable ones):**
- OS: Ubuntu Server
- Java version: openjdk version "17.0.7" 2023-04-18
- Mork version: v0.17 SNAPSHOT

**Comment by rmartinsanta** [comment]
@isaaclo97 I have improved the allowed automatic type conversions between numeric and boolean types, could you check if it covers all your use cases?
If not, please provide a short example class that reproduces the error

**Comment by isaaclo97** [comment]
Fixed @rmartinsanta, it works perfectly.
