### ISSUE TITLE
Autoconfig/IRACE with parallel methods 

### ISSUE THREAD

**Issue by isaaclo97** [mork-optimization/mork#171]
**Describe the bug**
Error when launching algorithm with Autoconfig method.

**To Reproduce**
Execution of personal project with autoconfig with parallel and non-parallelized algorithms.

**Expected behavior**
IRACE configuration with Autoconfig method.

**What happens instead**
Exception in thread.

**Screenshots / Code snippets**
```
Exception in thread "pool-12191-thread-44" java.lang.IllegalStateException: Called MetricsManager::getInstance before MetricsManager::resetMetrics
        at es.urjc.etsii.grafo.solution.metrics.MetricsManager.getInstance(MetricsManager.java:30)
        at es.urjc.etsii.grafo.solution.metrics.MetricsManager.addDatapoint(MetricsManager.java:108)
        at es.urjc.etsii.grafo.improve.Improver.improve(Improver.java:61)
        at es.urjc.etsii.grafo.CPIF.constructives.BVNSParalelo$1.run(BVNSParalelo.java:150)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Versions (ignore not applicable ones):**
- OS: Ubuntu Server
- Java version: openjdk version "17.0.7" 2023-04-18
- Mork version: v0.17 SNAPSHOT

**Additional context**
They have been tested with sequential algorithms and it also fails (either by launching 1 thread from the thread queue or without using concurrency).

**Comment by rmartinsanta** [comment]
It fails because Metrics are ThreadLocal, this needs more careful review. Currently, parallelization inside tested algorithms is not supported when tuning using the autoconfig method.
Some random comments for the future: a ThreadFactory may not be enough as metric data needs to still be merged afterwards. A possible solution may be to provide users with a customized ExecutorService managed by the framework.
