### ISSUE TITLE
Redirect invalid configurations to other output file

### ISSUE THREAD

**Issue by isaaclo97** [mork-optimization/mork#174]
**Is your feature request related to a problem? Please describe.**
When error like java.lang.IllegalArgumentException are reported it is impossible to obtain the IRACE table.

**Error Describe**
```
java.lang.IllegalArgumentException: Metric bestobjective does not have any element before 1000000000, first element is at TimeValue[timeElapsed=1101168450, value=215.0]
	at es.urjc.etsii.grafo.solution.metrics.Metrics.areaUnderCurve(Metrics.java:89)
	at es.urjc.etsii.grafo.autoconfig.irace.IraceOrchestrator.singleExecution(IraceOrchestrator.java:327)
	at es.urjc.etsii.grafo.autoconfig.irace.IraceOrchestrator.iraceCallback(IraceOrchestrator.java:268)
	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.execute(ExecutionController.java:53)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

```

[15:35:29] WARN  .e.g.a.i.IraceOrchestrator : Algorithm takes too long to stop after time is up in instance pmed23_r025_R15.txt. Algorithm::toString MA{name=Simple, maxIter=1073741823, minIter=1073741823, maxIterWoutImp=1073741823, alg=S{c=BVNS{K=0.13, lock=java.lang.Object@56c73cf3, iterations=24, ls=VND{imprs=[es.urjc.etsii.grafo.CPIF.localSearch.LocalSearchSwapsConstructionDestrutionNew@191ddad9, es.urjc.etsii.grafo.improve.Improver$NullImprover@4a0d9afc, es.urjc.etsii.grafo.improve.Improver$NullImprover@67846b66]}}, i=[es.urjc.etsii.grafo.improve.Improver$SequentialImprover@84be3c1]}}
```

**Describe alternatives you've considered**
Create new error log file, thus provide not broken the IRACE tables.

**Comment by rmartinsanta** [comment]
The first error cause is because the AUC area is unbounded to the left, and in that case, I think the proper solution is reporting to IRACE that the configuration is invalid as it did not report f.o values in time. I like the idea of reporting failures to generate valid algorithm configurations to a different file, to the main log file as debug messages, and even expose them in real time via the API. This way, default tables generated by IRACE should appear as is and not broken.

If the % of invalid configurations is greater than a given threshold, we could still report it in the main log file.
