### ISSUE TITLE
Error building several algorithms with buildFromStringParams

### ISSUE THREAD

**Issue by isaaclo97** [mork-optimization/mork#181]
**Describe the bug**
Running several algorithms.add(builder.buildFromStringParams())) there is a problem related to same shortName, so Mork cannot perform several.

**To Reproduce**
In the experiment class duplicate to algorithms.add(builder.buildFromStringParams())) (modify one parameter being it differents) and run an experiment.

**Expected behavior**
Perform such us experiments as you want with buildFromStringParams.

**What happens instead**
```
 java.lang.IllegalArgumentException: Duplicated algorithm shortName in experiment ConstructiveExperiment. FIX: All algorithm getShortName()
````

**Screenshots / Code snippets**
```
[10:53:40] WARN  ebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'experimentManager' defined in URL [jar:file:/C:/Users/isaac/.m2/repository/es/urjc/etsii/grafo/mork/0.17-SNAPSHOT/mork-0.17-SNAPSHOT.jar!/es/urjc/etsii/grafo/experiment/ExperimentManager.class]: Failed to instantiate [es.urjc.etsii.grafo.experiment.ExperimentManager]: Constructor threw exception
[10:53:40] ERROR o.s.b.SpringApplication    : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'experimentManager' defined in URL [jar:file:/C:/Users/isaac/.m2/repository/es/urjc/etsii/grafo/mork/0.17-SNAPSHOT/mork-0.17-SNAPSHOT.jar!/es/urjc/etsii/grafo/experiment/ExperimentManager.class]: Failed to instantiate [es.urjc.etsii.grafo.experiment.ExperimentManager]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:326)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:314)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at es.urjc.etsii.grafo.solver.Mork.start(Mork.java:46)
	at es.urjc.etsii.grafo.solver.Mork.start(Mork.java:29)
	at es.urjc.etsii.grafo.CPIF.Main.main(Main.java:8)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [es.urjc.etsii.grafo.experiment.ExperimentManager]: Constructor threw exception
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:323)
	... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: Duplicated algorithm shortName in experiment ConstructiveExperiment. FIX: All algorithm getShortName() should be unique per experiment → Simple
	at es.urjc.etsii.grafo.experiment.ExperimentManager.validateAlgorithmNames(ExperimentManager.java:123)
	at es.urjc.etsii.grafo.experiment.ExperimentManager.<init>(ExperimentManager.java:62)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 21 common frames omitted
```

**Versions (ignore not applicable ones):**
- OS: Ubuntu Server and Windows 10
- Java version: openjdk version "17.0.7" 2023-04-18
- Mork version: v0.17 SNAPSHOT

**Comment by isaaclo97** [comment]
Fixed.
Just i checked it that the names are random, maybe mork could provide new accurate names using for example toString implemented method (if two algorithms have the same name, just  (X) or _X as duplicated file systems)

**Comment by rmartinsanta** [comment]
The random name generator can be surely improved, and maybe replaced with a different strategy, but the problem is that names using toString or similar approaches tend to be long and too verbose, and tend to do not properly summarize the differences between parameter values. I am open to any ideas of how to improve this point.
